
export const motivationalQuotes = [
  "Transforme seu corpo, uma repetição de cada vez",
  "A dor que você sente hoje será a força que você sentirá amanhã",
  "Não pare quando estiver cansado, pare quando terminar",
  "Seu único limite é você mesmo",
  "Grandes resultados exigem grandes ambições",
  "O sucesso não vem para você, você vai até ele",
  "Cada treino te deixa mais próximo do seu objetivo",
  "A força não vem da capacidade física, mas da vontade indomável",
  "Desafie-se e surpreenda-se",
  "O primeiro passo é sempre o mais difícil",
  "Seja mais forte que suas desculpas",
  "Progresso, não perfeição",
  "Você é mais corajoso do que acredita",
  "A consistência é a chave do sucesso",
  "Comece onde você está, use o que você tem",
  "Acredite em si mesmo e você estará no meio do caminho",
  "O treino de hoje é o corpo de amanhã",
  "Supere seus limites diariamente",
  "Cada gota de suor vale a pena",
  "Seja a melhor versão de si mesmo",
  "O impossível é apenas uma opinião",
  "Vença na sua mente e você vencerá na vida",
  "Disciplina é escolher entre o que você quer agora e o que você quer mais",
  "A motivação te faz começar, o hábito te faz continuar",
  "Você é o herói da sua própria história",
  "Cada série te aproxima do seu sonho",
  "A excelência não é um ato, mas um hábito",
  "Seja paciente com o processo",
  "O fracasso é apenas feedback",
  "Você nasceu para ser forte",
  "Conquiste seus medos através da ação",
  "A mudança começa no momento da decisão",
  "Seja obsessivo com seus objetivos",
  "A única competição é com quem você era ontem",
  "Transforme obstáculos em oportunidades",
  "Sua mente é seu maior músculo",
  "Resiliência é sua segunda natureza",
  "Cada dia é uma nova chance de melhorar",
  "Faça acontecer, não deixe acontecer",
  "Você tem o poder de mudar sua vida",
  "A força mental supera a força física",
  "Seja constante, não perfeito",
  "Seu potencial é infinito",
  "Aceite o desafio, colha as recompensas",
  "A perseverança é a chave de todas as conquistas",
  "Você é mais forte do que imagina",
  "O crescimento acontece fora da zona de conforto",
  "Foque no progresso, não na perfeição",
  "Sua jornada é única, celebre cada passo",
  "A determinação abre todas as portas",
  "Seja o CEO do seu corpo",
  "Cada treino é um investimento em você",
  "A coragem não é ausência do medo, é ação apesar dele",
  "Você controla sua própria narrativa",
  "Pequenos passos levam a grandes mudanças",
  "A vida começa no final da sua zona de conforto",
  "Seja implacável na busca dos seus sonhos",
  "A diferença entre ordinário e extraordinário é essa pequena 'extra'",
  "Você não precisa ser extremo, apenas consistente",
  "O que não te desafia, não te transforma",
  "Seja a energia que você quer atrair",
  "Crie hábitos que te levem ao sucesso",
  "Sua única limitação é sua imaginação",
  "A força vem da luta, não da vitória fácil",
  "Cada momento é uma nova oportunidade",
  "Você tem o poder de reescrever sua história",
  "A excelência é um processo, não um destino",
  "Seja a mudança que você quer ver",
  "O sucesso é a soma de pequenos esforços",
  "Você é o autor da sua transformação",
  "A atitude é tudo",
  "Supere-se todos os dias",
  "Sua mentalidade determina sua realidade",
  "Seja incansável na busca da excelência",
  "A força de vontade é seu superpoder",
  "Cada repetição te fortalece por dentro e por fora",
  "Você é mais capaz do que acredita",
  "A mudança real vem de dentro",
  "Seja a melhor versão de ontem, hoje",
  "O progresso é impossível sem mudança",
  "Sua dedicação de hoje é seu resultado de amanhã",
  "Foque na solução, não no problema",
  "Você tem o poder de escolher sua resposta",
  "A persistência é o caminho do êxito",
  "Seja maior que seus obstáculos",
  "Cada dia de treino é um dia de vitória",
  "Você está construindo a versão 2.0 de si mesmo",
  "A força está na mente, o corpo apenas obedece",
  "Seja o combustível da sua própria motivação",
  "O impossível se torna possível com persistência",
  "Você é o arquiteto do seu próprio destino",
  "A grandeza está em continuar quando parece impossível",
  "Sua determinação é sua maior aliada",
  "Cada gota de suor é um investimento no futuro",
  "Você nasceu para superar limites",
  "A confiança vem da preparação",
  "Seja relentless na busca dos seus objetivos",
  "O que você faz hoje ecoa na eternidade",
  "Você tem o DNA de um vencedor",
  "A mudança é dolorosa, mas necessária",
  "Seja a inspiração que você procura",
  "O sucesso é 1% inspiração e 99% transpiração",
  "Você é mais forte que qualquer desafio",
  "A maestria vem da repetição consciente",
  "Seja o exemplo que você quer seguir",
  "Cada treino é uma declaração de guerra contra a mediocridade"
];

export const getRandomQuote = (): string => {
  const randomIndex = Math.floor(Math.random() * motivationalQuotes.length);
  return motivationalQuotes[randomIndex];
};
